### ISSUE TITLE
[Question]: how to fix the weird light?

### ISSUE THREAD

**Issue by BochkaDeyalo** [XFactHD/FramedBlocks#449]
### Question

I built a year ago a spawn for my server, on version 1.16.5. Today I decided to move this world to the new version 1.19.2.
I remembered that I used to turn on the experimental light function in the forge config. I found this option, turned it on. It didn't help. I don't know how to solve this problem.
I play on 1.19.2 with shaders and rubidium. if you turn them off and even restart the game - it does not help.

p.s put the same world on an old backup of cubes 1.16.5, the problem did not solve. blocks look exactly the same as on 1.19.2
![Снимок экрана 2024-06-23 182412](https://github.com/XFactHD/FramedBlocks/assets/78365169/79c38fc5-5cbf-45a2-8848-0f13208e2ed4)
![Снимок экрана 2024-06-23 182429](https://github.com/XFactHD/FramedBlocks/assets/78365169/3a0e14cb-f8c7-4d26-a379-9d67e03aca0f)
![Снимок экрана 2024-06-23 182448](https://github.com/XFactHD/FramedBlocks/assets/78365169/0fba5823-2430-466c-9e0c-2c0c5df24410)
![Снимок экрана 2024-06-23 182510](https://github.com/XFactHD/FramedBlocks/assets/78365169/dd22ae04-f391-4004-9fb8-bb8f5009cec5)

**Comment by BochkaDeyalo** [comment]
I also read on the forum that it may help to play with the soft light option. it also does not help.

![Снимок экрана 2024-06-23 182901](https://github.com/XFactHD/FramedBlocks/assets/78365169/2af48ac0-aed4-47d4-b9de-d71722cb881b)

**Comment by XFactHD** [comment]
It looks like the blocks in question are set to emit light by clicking them with glowstone dust. Making a block emit light disables smooth lighting for it, causing it to stand out from surrounding blocks. This effect is significantly increased when shaders are enabled, which is why the glowing blocks stand out so much. This issue is somewhat mitigated in recent 1.20.1 versions of FramedBlocks and properly fixed in the 1.21 update. 1.19 will however not receive further updates. I would highly recommend skipping 1.19.2 and moving to 1.20.1.

**Comment by BochkaDeyalo** [comment]
> It looks like the blocks in question are set to emit light by clicking them with glowstone dust. Making a block emit light disables smooth lighting for it, causing it to stand out from surrounding blocks. This effect is significantly increased when shaders are enabled, which is why the glowing blocks stand out so much. This issue is somewhat mitigated in recent 1.20.1 versions of FramedBlocks and properly fixed in the 1.21 update. 1.19 will however not receive further updates. I would highly recommend skipping 1.19.2 and moving to 1.20.1.

The problem is that I used to build this building on 1.16.5 and there was no such problem. both with and without shaders.
I still have some old screenshots from there I can show you. There was no lighting problem there.
When I downloaded 1.16.5 again and opened this save, I saw the same problem. The problem here is definitely not with the update/shaders/rubidium

**Comment by BochkaDeyalo** [comment]
![2023-05-28_18 24 15](https://github.com/XFactHD/FramedBlocks/assets/78365169/8f16d685-8c27-417f-8591-36c56bcdcf2b)
![2023-05-28_18 24 34](https://github.com/XFactHD/FramedBlocks/assets/78365169/50c848dc-994e-4c2b-9f49-02fd090a752d)
![2023-05-28_18 08 12](https://github.com/XFactHD/FramedBlocks/assets/78365169/e98dd7e2-a135-45ed-b17c-7cafa024fc5e)
![2023-05-28_18 20 47](https://github.com/XFactHD/FramedBlocks/assets/78365169/19ccd208-e3de-407b-b6c3-b1e6cf776c0b)
![2023-05-28_18 21 00](https://github.com/XFactHD/FramedBlocks/assets/78365169/984fb088-cf3c-4548-b8ce-0fd736982aa6)

**Comment by XFactHD** [comment]
As far as I can see, none of the framed blocks in these screenshots emit lights, so the issue of course does not occur. This issue specifically affects framed blocks which emit light and the exaggerated effect is caused by shaders being used. As mentioned before, this issue is mitigated in 1.20.1 and properly fixed in 1.21.

**Comment by BochkaDeyalo** [comment]
> As far as I can see, none of the framed blocks in these screenshots emit lights, so the issue of course does not occur. This issue specifically affects framed blocks which emit light and the exaggerated effect is caused by shaders being used. As mentioned before, this issue is mitigated in 1.20.1 and properly fixed in 1.21.

This is an old map, I have not modified it in any way since then. I just restored the save.

**Comment by BochkaDeyalo** [comment]
> As far as I can see, none of the framed blocks in these screenshots emit lights, so the issue of course does not occur. This issue specifically affects framed blocks which emit light and the exaggerated effect is caused by shaders being used. As mentioned before, this issue is mitigated in 1.20.1 and properly fixed in 1.21.

unfortunately, the developer community does not have time to port their mods to the latest versions. as much as I would like to play on the latest versions with fixes and stuff, I can't do it.

even with Framed blocks, you can see that.

![image](https://github.com/XFactHD/FramedBlocks/assets/78365169/02b45a8d-803e-4611-bcec-3909e8e25ea8)
![image](https://github.com/XFactHD/FramedBlocks/assets/78365169/14dfed2a-a3fa-46e0-8570-b38b0fbb094e)
![image](https://github.com/XFactHD/FramedBlocks/assets/78365169/f16c58a1-3862-4085-9a11-6414e9614609)

**Comment by XFactHD** [comment]
> This is an old map, I have not modified it in any way since then. I just restored the save.

Something *must* have changed, otherwise the blocks wouldn't suddenly look completely different. Whether that's a change in the world itself or whether that's a mod update is not really relevant.
One final thing you can try is switching from Rubidium to Embeddium as the latter has significantly improved mod compatibility, that might fix the issue.

> unfortunately, the developer community does not have time to port their mods to the latest versions.

Minecraft moves forward and so do mod loaders and mods. Mods falling behind or getting abandoned entirely is just an unfortunate side-effect of that. Nothing is permanent when you're working with a moving target like Minecraft.
I will also note that your comparison between 1.19.2 and 1.20.1 doesn't make sense, you cannot compare a single file that was uploaded 10 months ago with a single file that was uploaded barely 3 weeks ago. With respect to the 1.21 version using NeoForge: a very large amount of mods are switching to it on 1.21 or have already done so between 1.20.2 and 1.21.
